# Generated by Django 5.0.7 on 2024-08-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
